### ISSUE TITLE
[Feature] Make connections through Tor network

### ISSUE THREAD

**Issue by RequestPrivacy** [j4imefoo/lsbisq#1]
Happy to summit a first issue here.

As Bisq users are very privacy aware, what about pulling the API data from the exchanges and Bisq via Tor?

Maybe through an option via a flag during the call?

**Comment by alkum** [comment]
For the bisq.markets API, see the `onion-location` header in the HTTP response (thats the onion address at which the API is reachable at via tor).

**Comment by j4imefoo** [comment]
Done! try --tor
