### ISSUE TITLE
case sensitive

### ISSUE THREAD

**Issue by decentralizedb** [j4imefoo/lsbisq#3]
Yesterday (21/03/2022), when releasing the first version I was testing the command-line putting in lower case the parameters and didn't have any problem.
Now (22/03/2022), with this new release, you need to enter in upper case, for example, EUR and not accept eur.

First release:
./lsbisq.py -r fiat eur

Now:
/lsbisq.py -t BUY -f EUR

I think is better to have the possibility to enter in both, lower & upper case.
![image](https://user-images.githubusercontent.com/58108487/159479021-39a16a58-cd07-4902-902f-36df2c8668a1.png)

**Comment by j4imefoo** [comment]
In reality, yesterday it didn't accept any more parameters than "-r". The rest of paramenters "fiat eur" were just ignored (you could config them by manually editing the script). Now the script has the option of indicating the fiat currency, which is in caps but it is well indicated in the command line (type lsbisq -h) and will be documented in the README files

**Comment by decentralizedb** [comment]
> In reality, yesterday it didn't accept any more parameters than "-r". The rest of paramenters "fiat eur" were just ignored (you could config them by manually editing the script). Now the script has the option of indicating the fiat currency, which is in caps but it is well indicated in the command line (type lsbisq -h) and will be documented in the README files

Ok, thanks for the clarification. I thought that the parameters were taken from the command line.

As a UX, don't you think it's better not to force parameters should be uppercase? (an improvement)
